# Generated by Django 2.1.3 on 2022-03-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('入住时间', models.CharField(blank=True, max_length=45, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accommodation',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('顾客id', models.AutoField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(blank=True, max_length=45, null=True)),
                ('身份证号', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('菜品编号', models.IntegerField(primary_key=True, serialize=False)),
                ('菜名', models.CharField(max_length=45)),
                ('价格', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('桌号', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('车位编号', models.IntegerField(primary_key=True, serialize=False)),
                ('当前状态', models.CharField(max_length=45)),
                ('车辆牌号', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'park',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('房间号', models.IntegerField(primary_key=True, serialize=False)),
                ('客房类型', models.CharField(max_length=45)),
                ('价格', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('员工id', models.AutoField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=45)),
                ('职务', models.CharField(max_length=45)),
                ('月薪', models.CharField(max_length=45)),
                ('工龄', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('会员编号', models.AutoField(primary_key=True, serialize=False)),
                ('姓名', models.CharField(max_length=45)),
                ('会员等级', models.CharField(max_length=45)),
                ('联系方式', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vip',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='负责人编号',
            field=models.ForeignKey(db_column='负责人编号', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='服务员编号',
            field=models.ForeignKey(db_column='服务员编号', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='菜品编号',
            field=models.ForeignKey(db_column='菜品编号', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='顾客编号',
            field=models.ForeignKey(db_column='顾客编号', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Client'),
        ),
        migrations.AddField(
            model_name='food',
            name='厨师id',
            field=models.ForeignKey(db_column='厨师id', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Staff'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='客房编号',
            field=models.ForeignKey(db_column='客房编号', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Room'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='顾客id',
            field=models.ForeignKey(db_column='顾客id', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Client'),
        ),
    ]
